# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    exception:
        enabled: true
    format_listener:
        rules:
            - { path: "^/api", priorities: ["json"], fallback_format: "json", prefer_extension: false }
            - { path: '^/', priorities: [ 'text/html', 'application/json', '*/*'], fallback_format: html, prefer_extension: false, stop: true }}
    body_listener:
        decoders:
            json: acme.decoder.json
    view:
        view_response_listener: true
    serializer:
        serialize_null: true
