nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['*']
    allow_headers: ['*']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS','PATCH']
    expose_headers: []
    max_age: 3600
    hosts: []
    origin_regex: false
    forced_allow_origin_value: ~
    skip_same_as_origin: true
  paths:
    '^/api/':
      allow_credentials: true
      allow_headers: ['*']
      allow_origin: ['http://localhost:4200']
      allow_methods: ['POST', 'PUT', 'GET', 'DELETE','PATCH']
      max_age: 3600
    '^/':
      origin_regex: true
      allow_origin: ['^http://localhost:[0-9]+']
      allow_headers: ['X-Custom-Auth']
      allow_methods: ['POST', 'PUT', 'GET', 'DELETE','PATCH']
      max_age: 3600
      hosts: ['^api\.']