controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    # webhook:
    #     resource: '@FrameworkBundle/Resources/config/routing/webhook.xml'
    #     prefix: /webhook


app.swagger_ui:
    path: /api/v1/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/v1/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
