security:

  # Note: Only the *first* access control that matches will be used
  access_control:
    - {
      path: ^/api/v1/doc,
      roles: PUBLIC_ACCESS,
      methods: [ GET, POST, PUT, PATCH, DELETE ],
    }